#' @title PI-MIMIC Graphics: EPC and SEPC
#'
#' @description
#' The `piRFA.plot()` function generates bar plots of EPC (EPC and SEPC.ALL) coefficients for uniform and non-uniform DIF, facilitating the interpretation of DIF effects in items evaluated by the \code{\link{piRFA}} function.
#'
#' @param resultados List of results generated by \code{\link{piRFA}}.
#' @param cov Name of the covariate used in \code{\link{piRFA}}.
#' @param metric Metric to plot: either `"EPC"` or `"SEPC.ALL"` (default is `"SEPC.ALL"`).
#' @param theme_option ggplot2 theme (default is `theme_minimal()`).
#' @param bar_colors Colors for the types of DIF (default blue and red, named `"Uniform DIF"` and `"Non-uniform DIF"`).
#' @param cutoff_line Horizontal line(s) indicating the DIF cutoff (default `0.10`). Can be a vector, e.g., `c(-0.10, 0.10)`.
#'
#' @return
#' A bar plot of EPC or SEPC coefficients for uniform and non-uniform DIF.
#'
#' @details
#' \code{\link{piRFA.plot}} takes the output from \code{\link{piRFA}}, focused on the unstandardized (EPC) or standardized (SEPC.ALL) metric of the expected parameter change. The user must choose which metric to plot.
#'
#' @examples
#' set.seed(123)
#' Exmp1.data <- data.frame(
#'   grp = sample(0:1, 100, replace = TRUE),  # Group variable
#'   item1 = sample(1:5, 100, replace = TRUE),
#'   item2 = sample(1:5, 100, replace = TRUE),
#'   item3 = sample(1:5, 100, replace = TRUE))
#'
#' Exmp1.output <- piRFA(data = Exmp1.data, items = c("Item1", "Item2", "Item3"), cov = "grp")
#'
#' # Plot standardized expected parameter change (SEPC.ALL)
#' piRFA.plot(Exmp1.output, cov = "grp")
#'
#' # Plot with a custom cutoff range
#' piRFA.plot(Exmp1.output, cov = "grp", cutoff_line = c(-.10, .10))
#'
#' # Plot unstandardized expected parameter change (EPC)
#' piRFA.plot(Exmp1.output, cov = "grp", metric = "EPC")
#'
#' @seealso
#' \code{\link{ggplot2}}, \code{\link{piRFA}}
#'
#' @export
#' @import ggplot2
piRFA.plot <- function(resultados, cov,
                       metric = "SEPC.ALL",
                       theme_option = theme_minimal(),
                       bar_colors = c("Uniform DIF" = "blue", "Non-uniform DIF" = "red"),
                       cutoff_line = 0.10) {
  # Validate 'metric' argument
  if (!metric %in% c("EPC", "SEPC.ALL")) {
    stop("Error: The 'metric' argument must be 'EPC' or 'SEPC.ALL'.")
  }

  # Extract SEPC data according to selected metric
  df_sepc <- resultados$SEPC

  # Check if SEPC has data
  if (nrow(df_sepc) > 0) {
    cov_lat <- paste0(cov, "lat")
    fac_interaction <- paste0("LFacX", cov)
    # Dynamically filter SEPC rows for the covariate used
    df_sepc_filtered <- df_sepc[grepl(paste0(cov_lat, "|", fac_interaction), df_sepc$Effect), ]
    # Correct DIF type names
    df_sepc_filtered$Type <- ifelse(grepl(cov_lat, df_sepc_filtered$Effect),
                                    "Uniform DIF", "Non-uniform DIF")
    df_sepc_filtered$Type <- factor(df_sepc_filtered$Type, levels = c("Uniform DIF", "Non-uniform DIF"))
    # Generate plot with the selected metric
    p1 <- ggplot(df_sepc_filtered, aes(x = Item, y = !!sym(metric), fill = Type)) +
      geom_bar(stat = "identity", position = "dodge") +
      geom_hline(yintercept = cutoff_line, linetype = "dashed", color = "black") +
      coord_flip() +
      labs(title = paste(metric, "by Item - Covariate:", cov),
           x = "Items",
           y = paste("Standardized", metric)) +
      scale_fill_manual(values = bar_colors) +
      theme_option
    print(p1)
  } else {
    cat("Insufficient data to generate the SEPC plot.\n")
  }
}
